### ISSUE TITLE
Hello. My name is Minh 

### ISSUE THREAD

**Issue by nhimxu00** [Bruno-Messias/Yolo_traffic_signs_recognition#1]
Thank you for creating a great project! I'm currently a student, but I see that your project is missing the data part, but I'm currently working on a project like this. Thank you very much if you can share the data part of the obj.zip file for me.
you can contact me via fb: https://www.facebook.com/NhimXoanXu/
Have a nice day !
Love

**Comment by Bruno-Messias** [comment]
Hello @nhimxu00! I'm glad that you like my project.

I just update the files with this obj.zip, you can now found [here](https://drive.google.com/drive/folders/1Fj0tr7Y7bYVV2gMpQhSrrouz6_Xrrdz6).

Actually, this data I get from this  [Kaagle](https://www.kaggle.com/valentynsichkar/traffic-signs-dataset-in-yolo-format), you can found more codes and projects their that can help you!

Have a nice day too !
